//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarket.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessagesPT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessagesPT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smarket.API.Resources.GeneralMessagesPT", typeof(GeneralMessagesPT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar marca por descrição.
        /// </summary>
        public static string GetBrandByDescriptionError {
            get {
                return ResourceManager.GetString("GetBrandByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca recebida com sucesso.
        /// </summary>
        public static string GetBrandByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetBrandByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar marca por id.
        /// </summary>
        public static string GetBrandByIdError {
            get {
                return ResourceManager.GetString("GetBrandByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca recebida com sucesso.
        /// </summary>
        public static string GetBrandByIdSuccess {
            get {
                return ResourceManager.GetString("GetBrandByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de marcas.
        /// </summary>
        public static string GetBrandsError {
            get {
                return ResourceManager.GetString("GetBrandsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de marcas recebidas com sucesso.
        /// </summary>
        public static string GetBrandsSuccess {
            get {
                return ResourceManager.GetString("GetBrandsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de categorias.
        /// </summary>
        public static string GetCategoriesError {
            get {
                return ResourceManager.GetString("GetCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de categorias recebidas com sucesso.
        /// </summary>
        public static string GetCategoriesSuccess {
            get {
                return ResourceManager.GetString("GetCategoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar categoria por descrição.
        /// </summary>
        public static string GetCategoryByDescriptionError {
            get {
                return ResourceManager.GetString("GetCategoryByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria recebida com sucesso.
        /// </summary>
        public static string GetCategoryByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetCategoryByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar categoria por Id.
        /// </summary>
        public static string GetCategoryByIdError {
            get {
                return ResourceManager.GetString("GetCategoryByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria recebida com sucesso.
        /// </summary>
        public static string GetCategoryByIdSuccess {
            get {
                return ResourceManager.GetString("GetCategoryByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de cidades.
        /// </summary>
        public static string GetCitiesError {
            get {
                return ResourceManager.GetString("GetCitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de cidades recebidas com sucesso.
        /// </summary>
        public static string GetCitiesSuccess {
            get {
                return ResourceManager.GetString("GetCitiesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de estabelecimentos consumidores.
        /// </summary>
        public static string GetCommercesError {
            get {
                return ResourceManager.GetString("GetCommercesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de estabelecimentos consumidores recebida com sucesso.
        /// </summary>
        public static string GetCommercesSuccess {
            get {
                return ResourceManager.GetString("GetCommercesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de consumidores.
        /// </summary>
        public static string GetConsumersError {
            get {
                return ResourceManager.GetString("GetConsumersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de consumidores recebida com sucesso.
        /// </summary>
        public static string GetConsumersSuccess {
            get {
                return ResourceManager.GetString("GetConsumersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar token.
        /// </summary>
        public static string GetGeneratedTokenError {
            get {
                return ResourceManager.GetString("GetGeneratedTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token gerado com sucesso.
        /// </summary>
        public static string GetGeneratedTokenSuccess {
            get {
                return ResourceManager.GetString("GetGeneratedTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar lote pela descrição.
        /// </summary>
        public static string GetLotByDescriptionError {
            get {
                return ResourceManager.GetString("GetLotByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote recebido com sucesso.
        /// </summary>
        public static string GetLotByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetLotByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar lot por id.
        /// </summary>
        public static string GetLotByIdError {
            get {
                return ResourceManager.GetString("GetLotByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote recebido com sucesso.
        /// </summary>
        public static string GetLotByIdSuccess {
            get {
                return ResourceManager.GetString("GetLotByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar lote(s) por mercado.
        /// </summary>
        public static string GetLotsByMarketError {
            get {
                return ResourceManager.GetString("GetLotsByMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote(s) recebido(s) com sucesso.
        /// </summary>
        public static string GetLotsByMarketSuccess {
            get {
                return ResourceManager.GetString("GetLotsByMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar lote(s) por produto.
        /// </summary>
        public static string GetLotsByProductError {
            get {
                return ResourceManager.GetString("GetLotsByProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote(s) recebido(s) com sucesso.
        /// </summary>
        public static string GetLotsByProductSuccess {
            get {
                return ResourceManager.GetString("GetLotsByProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de lotes.
        /// </summary>
        public static string GetLotsError {
            get {
                return ResourceManager.GetString("GetLotsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de lotes recebida com sucesso.
        /// </summary>
        public static string GetLotsSuccess {
            get {
                return ResourceManager.GetString("GetLotsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de mercados.
        /// </summary>
        public static string GetMarketsError {
            get {
                return ResourceManager.GetString("GetMarketsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de mercados recebida com sucesso.
        /// </summary>
        public static string GetMarketsSuccess {
            get {
                return ResourceManager.GetString("GetMarketsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar produto(s) pela marca.
        /// </summary>
        public static string GetProductByBrandError {
            get {
                return ResourceManager.GetString("GetProductByBrandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto(s) recebido com sucesso.
        /// </summary>
        public static string GetProductByBrandSuccess {
            get {
                return ResourceManager.GetString("GetProductByBrandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar produto pela descrição.
        /// </summary>
        public static string GetProductByDescriptionError {
            get {
                return ResourceManager.GetString("GetProductByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto recebido com sucesso.
        /// </summary>
        public static string GetProductByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetProductByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar produto por id.
        /// </summary>
        public static string GetProductByIdError {
            get {
                return ResourceManager.GetString("GetProductByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto recebido com sucesso.
        /// </summary>
        public static string GetProductByIdSuccess {
            get {
                return ResourceManager.GetString("GetProductByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar produto(s) por mercado.
        /// </summary>
        public static string GetProductsByMarketError {
            get {
                return ResourceManager.GetString("GetProductsByMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto(s) recebido(s) com sucesso.
        /// </summary>
        public static string GetProductsByMarketSuccess {
            get {
                return ResourceManager.GetString("GetProductsByMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar produto(s) por subcategoria.
        /// </summary>
        public static string GetProductsBySubCategoryError {
            get {
                return ResourceManager.GetString("GetProductsBySubCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto(s) recebido(s) com sucesso.
        /// </summary>
        public static string GetProductsBySubCategorySuccess {
            get {
                return ResourceManager.GetString("GetProductsBySubCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de produtos.
        /// </summary>
        public static string GetProductsError {
            get {
                return ResourceManager.GetString("GetProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de produtos recebida com sucesso.
        /// </summary>
        public static string GetProductsSuccess {
            get {
                return ResourceManager.GetString("GetProductsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de estados.
        /// </summary>
        public static string GetStatesError {
            get {
                return ResourceManager.GetString("GetStatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de estados recebidas com sucesso.
        /// </summary>
        public static string GetStatesSuccess {
            get {
                return ResourceManager.GetString("GetStatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de subcategorias.
        /// </summary>
        public static string GetSubCategoriesError {
            get {
                return ResourceManager.GetString("GetSubCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de subcategorias com sucesso.
        /// </summary>
        public static string GetSubCategoriesSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar subcategoria(s) por categoria.
        /// </summary>
        public static string GetSubCategoryByCategoryError {
            get {
                return ResourceManager.GetString("GetSubCategoryByCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoria(s) recebida(s) com sucesso.
        /// </summary>
        public static string GetSubCategoryByCategorySuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar subcategoria por descrição.
        /// </summary>
        public static string GetSubCategoryByDescriptionError {
            get {
                return ResourceManager.GetString("GetSubCategoryByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoria recebida com sucesso.
        /// </summary>
        public static string GetSubCategoryByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar subcategoria por id.
        /// </summary>
        public static string GetSubCategoryByIdError {
            get {
                return ResourceManager.GetString("GetSubCategoryByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoria recebida com sucesso.
        /// </summary>
        public static string GetSubCategoryByIdSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber lista de usúarios.
        /// </summary>
        public static string GetUsersError {
            get {
                return ResourceManager.GetString("GetUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de usúarios recebida com sucesso.
        /// </summary>
        public static string GetUsersSuccess {
            get {
                return ResourceManager.GetString("GetUsersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, marca já existe na base.
        /// </summary>
        public static string SaveBrandAlreadyExists {
            get {
                return ResourceManager.GetString("SaveBrandAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar marca.
        /// </summary>
        public static string SaveBrandError {
            get {
                return ResourceManager.GetString("SaveBrandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca salva com sucesso.
        /// </summary>
        public static string SaveBrandSuccess {
            get {
                return ResourceManager.GetString("SaveBrandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, categoria já existe na base.
        /// </summary>
        public static string SaveCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("SaveCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar categoria.
        /// </summary>
        public static string SaveCategoryError {
            get {
                return ResourceManager.GetString("SaveCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria salva com sucesso.
        /// </summary>
        public static string SaveCategorySuccess {
            get {
                return ResourceManager.GetString("SaveCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, estabelecimento consumidor já existe na base.
        /// </summary>
        public static string SaveCommerceAlreadyExists {
            get {
                return ResourceManager.GetString("SaveCommerceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar estabelecimento consumidor.
        /// </summary>
        public static string SaveCommerceError {
            get {
                return ResourceManager.GetString("SaveCommerceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento consumidor salvo com sucesso.
        /// </summary>
        public static string SaveCommerceSuccess {
            get {
                return ResourceManager.GetString("SaveCommerceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar consumidor.
        /// </summary>
        public static string SaveConsumerError {
            get {
                return ResourceManager.GetString("SaveConsumerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumidor salvo com sucesso.
        /// </summary>
        public static string SaveConsumerSuccess {
            get {
                return ResourceManager.GetString("SaveConsumerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, lote já existe na base.
        /// </summary>
        public static string SaveLotAlreadyExists {
            get {
                return ResourceManager.GetString("SaveLotAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar lote.
        /// </summary>
        public static string SaveLotError {
            get {
                return ResourceManager.GetString("SaveLotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote salvo com sucesso.
        /// </summary>
        public static string SaveLotSuccess {
            get {
                return ResourceManager.GetString("SaveLotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, mercado já existe na base.
        /// </summary>
        public static string SaveMarketAlreadyExists {
            get {
                return ResourceManager.GetString("SaveMarketAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar mercado.
        /// </summary>
        public static string SaveMarketError {
            get {
                return ResourceManager.GetString("SaveMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercado salvo com sucesso.
        /// </summary>
        public static string SaveMarketSuccess {
            get {
                return ResourceManager.GetString("SaveMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar telefone.
        /// </summary>
        public static string SavePhoneError {
            get {
                return ResourceManager.GetString("SavePhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone salvo com sucesso.
        /// </summary>
        public static string SavePhoneSuccess {
            get {
                return ResourceManager.GetString("SavePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, produto já existe na base.
        /// </summary>
        public static string SaveProductAlreadyExists {
            get {
                return ResourceManager.GetString("SaveProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar produto.
        /// </summary>
        public static string SaveProductError {
            get {
                return ResourceManager.GetString("SaveProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto salvo com sucesso.
        /// </summary>
        public static string SaveProductSuccess {
            get {
                return ResourceManager.GetString("SaveProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, Subcategoria já existe na base.
        /// </summary>
        public static string SaveSubCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("SaveSubCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar subcategoria.
        /// </summary>
        public static string SaveSubCategoryError {
            get {
                return ResourceManager.GetString("SaveSubCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoria salva com sucesso.
        /// </summary>
        public static string SaveSubCategorySuccess {
            get {
                return ResourceManager.GetString("SaveSubCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, usúario já existe na base.
        /// </summary>
        public static string SaveUserAlreadyExists {
            get {
                return ResourceManager.GetString("SaveUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar usúario.
        /// </summary>
        public static string SaveUserError {
            get {
                return ResourceManager.GetString("SaveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usúario salvo com sucesso.
        /// </summary>
        public static string SaveUserSuccess {
            get {
                return ResourceManager.GetString("SaveUserSuccess", resourceCulture);
            }
        }
    }
}
