//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarket.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessagesEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessagesEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smarket.API.Resources.GeneralMessagesEN", typeof(GeneralMessagesEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching brand by description.
        /// </summary>
        public static string GetBrandByDescriptionError {
            get {
                return ResourceManager.GetString("GetBrandByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand successfully received.
        /// </summary>
        public static string GetBrandByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetBrandByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching brand by id.
        /// </summary>
        public static string GetBrandByIdError {
            get {
                return ResourceManager.GetString("GetBrandByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand successfully received.
        /// </summary>
        public static string GetBrandByIdSuccess {
            get {
                return ResourceManager.GetString("GetBrandByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of brands.
        /// </summary>
        public static string GetBrandsError {
            get {
                return ResourceManager.GetString("GetBrandsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of brands successfully received.
        /// </summary>
        public static string GetBrandsSuccess {
            get {
                return ResourceManager.GetString("GetBrandsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of categories.
        /// </summary>
        public static string GetCategoriesError {
            get {
                return ResourceManager.GetString("GetCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of categories successfully received.
        /// </summary>
        public static string GetCategoriesSuccess {
            get {
                return ResourceManager.GetString("GetCategoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching category by description.
        /// </summary>
        public static string GetCategoryByDescriptionError {
            get {
                return ResourceManager.GetString("GetCategoryByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category successfully received.
        /// </summary>
        public static string GetCategoryByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetCategoryByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching category by Id.
        /// </summary>
        public static string GetCategoryByIdError {
            get {
                return ResourceManager.GetString("GetCategoryByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category successfully received.
        /// </summary>
        public static string GetCategoryByIdSuccess {
            get {
                return ResourceManager.GetString("GetCategoryByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of cities.
        /// </summary>
        public static string GetCitiesError {
            get {
                return ResourceManager.GetString("GetCitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of cities successfully received.
        /// </summary>
        public static string GetCitiesSuccess {
            get {
                return ResourceManager.GetString("GetCitiesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of commerces.
        /// </summary>
        public static string GetCommercesError {
            get {
                return ResourceManager.GetString("GetCommercesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of commerces successfully received.
        /// </summary>
        public static string GetCommercesSuccess {
            get {
                return ResourceManager.GetString("GetCommercesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of consumers.
        /// </summary>
        public static string GetConsumersError {
            get {
                return ResourceManager.GetString("GetConsumersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of consumers successfully received.
        /// </summary>
        public static string GetConsumersSuccess {
            get {
                return ResourceManager.GetString("GetConsumersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating token.
        /// </summary>
        public static string GetGeneratedTokenError {
            get {
                return ResourceManager.GetString("GetGeneratedTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully generated Token.
        /// </summary>
        public static string GetGeneratedTokenSuccess {
            get {
                return ResourceManager.GetString("GetGeneratedTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching lot by description.
        /// </summary>
        public static string GetLotByDescriptionError {
            get {
                return ResourceManager.GetString("GetLotByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot successfully received.
        /// </summary>
        public static string GetLotByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetLotByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching lot by id.
        /// </summary>
        public static string GetLotByIdError {
            get {
                return ResourceManager.GetString("GetLotByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot successfully received.
        /// </summary>
        public static string GetLotByIdSuccess {
            get {
                return ResourceManager.GetString("GetLotByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching lot by market.
        /// </summary>
        public static string GetLotsByMarketError {
            get {
                return ResourceManager.GetString("GetLotsByMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful lot received.
        /// </summary>
        public static string GetLotsByMarketSuccess {
            get {
                return ResourceManager.GetString("GetLotsByMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching lot by product.
        /// </summary>
        public static string GetLotsByProductError {
            get {
                return ResourceManager.GetString("GetLotsByProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful lot received.
        /// </summary>
        public static string GetLotsByProductSuccess {
            get {
                return ResourceManager.GetString("GetLotsByProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving lot list.
        /// </summary>
        public static string GetLotsError {
            get {
                return ResourceManager.GetString("GetLotsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot list successfully received.
        /// </summary>
        public static string GetLotsSuccess {
            get {
                return ResourceManager.GetString("GetLotsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of markets.
        /// </summary>
        public static string GetMarketsError {
            get {
                return ResourceManager.GetString("GetMarketsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of markets successfully received.
        /// </summary>
        public static string GetMarketsSuccess {
            get {
                return ResourceManager.GetString("GetMarketsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching products by brand.
        /// </summary>
        public static string GetProductByBrandError {
            get {
                return ResourceManager.GetString("GetProductByBrandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products received successfully.
        /// </summary>
        public static string GetProductByBrandSuccess {
            get {
                return ResourceManager.GetString("GetProductByBrandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching product by description.
        /// </summary>
        public static string GetProductByDescriptionError {
            get {
                return ResourceManager.GetString("GetProductByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully received.
        /// </summary>
        public static string GetProductByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetProductByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching product by id.
        /// </summary>
        public static string GetProductByIdError {
            get {
                return ResourceManager.GetString("GetProductByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully received.
        /// </summary>
        public static string GetProductByIdSuccess {
            get {
                return ResourceManager.GetString("GetProductByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching products by market.
        /// </summary>
        public static string GetProductsByMarketError {
            get {
                return ResourceManager.GetString("GetProductsByMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products received successfully.
        /// </summary>
        public static string GetProductsByMarketSuccess {
            get {
                return ResourceManager.GetString("GetProductsByMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching products by subcategory.
        /// </summary>
        public static string GetProductsBySubCategoryError {
            get {
                return ResourceManager.GetString("GetProductsBySubCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products received successfully.
        /// </summary>
        public static string GetProductsBySubCategorySuccess {
            get {
                return ResourceManager.GetString("GetProductsBySubCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving product list.
        /// </summary>
        public static string GetProductsError {
            get {
                return ResourceManager.GetString("GetProductsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of products received successfully.
        /// </summary>
        public static string GetProductsSuccess {
            get {
                return ResourceManager.GetString("GetProductsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving states list.
        /// </summary>
        public static string GetStatesError {
            get {
                return ResourceManager.GetString("GetStatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of successfully received states.
        /// </summary>
        public static string GetStatesSuccess {
            get {
                return ResourceManager.GetString("GetStatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of subcategories.
        /// </summary>
        public static string GetSubCategoriesError {
            get {
                return ResourceManager.GetString("GetSubCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of subcategories successfully.
        /// </summary>
        public static string GetSubCategoriesSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching subcategories by category.
        /// </summary>
        public static string GetSubCategoryByCategoryError {
            get {
                return ResourceManager.GetString("GetSubCategoryByCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories successfully received.
        /// </summary>
        public static string GetSubCategoryByCategorySuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching subcategory by description.
        /// </summary>
        public static string GetSubCategoryByDescriptionError {
            get {
                return ResourceManager.GetString("GetSubCategoryByDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory received successfully.
        /// </summary>
        public static string GetSubCategoryByDescriptionSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching subcategory by id.
        /// </summary>
        public static string GetSubCategoryByIdError {
            get {
                return ResourceManager.GetString("GetSubCategoryByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory received successfully.
        /// </summary>
        public static string GetSubCategoryByIdSuccess {
            get {
                return ResourceManager.GetString("GetSubCategoryByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving list of users.
        /// </summary>
        public static string GetUsersError {
            get {
                return ResourceManager.GetString("GetUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users successfully received.
        /// </summary>
        public static string GetUsersSuccess {
            get {
                return ResourceManager.GetString("GetUsersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, brand already exists in base.
        /// </summary>
        public static string SaveBrandAlreadyExists {
            get {
                return ResourceManager.GetString("SaveBrandAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving branding.
        /// </summary>
        public static string SaveBrandError {
            get {
                return ResourceManager.GetString("SaveBrandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand saved successfully.
        /// </summary>
        public static string SaveBrandSuccess {
            get {
                return ResourceManager.GetString("SaveBrandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, category already exists in base.
        /// </summary>
        public static string SaveCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("SaveCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving category.
        /// </summary>
        public static string SaveCategoryError {
            get {
                return ResourceManager.GetString("SaveCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category saved successfully.
        /// </summary>
        public static string SaveCategorySuccess {
            get {
                return ResourceManager.GetString("SaveCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, commerce already exists in base.
        /// </summary>
        public static string SaveCommerceAlreadyExists {
            get {
                return ResourceManager.GetString("SaveCommerceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving commerce.
        /// </summary>
        public static string SaveCommerceError {
            get {
                return ResourceManager.GetString("SaveCommerceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerce saved successfully.
        /// </summary>
        public static string SaveCommerceSuccess {
            get {
                return ResourceManager.GetString("SaveCommerceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving consumer.
        /// </summary>
        public static string SaveConsumerError {
            get {
                return ResourceManager.GetString("SaveConsumerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer saved successfully.
        /// </summary>
        public static string SaveConsumerSuccess {
            get {
                return ResourceManager.GetString("SaveConsumerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, lot already exists in base.
        /// </summary>
        public static string SaveLotAlreadyExists {
            get {
                return ResourceManager.GetString("SaveLotAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving lot.
        /// </summary>
        public static string SaveLotError {
            get {
                return ResourceManager.GetString("SaveLotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot saved successfully.
        /// </summary>
        public static string SaveLotSuccess {
            get {
                return ResourceManager.GetString("SaveLotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, market already exists in base.
        /// </summary>
        public static string SaveMarketAlreadyExists {
            get {
                return ResourceManager.GetString("SaveMarketAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving market.
        /// </summary>
        public static string SaveMarketError {
            get {
                return ResourceManager.GetString("SaveMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market saved successfully.
        /// </summary>
        public static string SaveMarketSuccess {
            get {
                return ResourceManager.GetString("SaveMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving phone.
        /// </summary>
        public static string SavePhoneError {
            get {
                return ResourceManager.GetString("SavePhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone saved successfully.
        /// </summary>
        public static string SavePhoneSuccess {
            get {
                return ResourceManager.GetString("SavePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, product already exists in base.
        /// </summary>
        public static string SaveProductAlreadyExists {
            get {
                return ResourceManager.GetString("SaveProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving product.
        /// </summary>
        public static string SaveProductError {
            get {
                return ResourceManager.GetString("SaveProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product saved successfully.
        /// </summary>
        public static string SaveProductSuccess {
            get {
                return ResourceManager.GetString("SaveProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Subcategory already exists in base.
        /// </summary>
        public static string SaveSubCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("SaveSubCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving subcategory.
        /// </summary>
        public static string SaveSubCategoryError {
            get {
                return ResourceManager.GetString("SaveSubCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory saved successfully.
        /// </summary>
        public static string SaveSubCategorySuccess {
            get {
                return ResourceManager.GetString("SaveSubCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, user already exists in base.
        /// </summary>
        public static string SaveUserAlreadyExists {
            get {
                return ResourceManager.GetString("SaveUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving user.
        /// </summary>
        public static string SaveUserError {
            get {
                return ResourceManager.GetString("SaveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully.
        /// </summary>
        public static string SaveUserSuccess {
            get {
                return ResourceManager.GetString("SaveUserSuccess", resourceCulture);
            }
        }
    }
}
