//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarket.API.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessagesPT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessagesPT() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smarket.API.Resources.GeneralMessagesPT", typeof(GeneralMessagesPT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de cidades.
        /// </summary>
        public static string GetCitiesError {
            get {
                return ResourceManager.GetString("GetCitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de cidades recebidas com sucesso.
        /// </summary>
        public static string GetCitiesSuccess {
            get {
                return ResourceManager.GetString("GetCitiesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de estabelecimentos consumidores.
        /// </summary>
        public static string GetCommercesError {
            get {
                return ResourceManager.GetString("GetCommercesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de estabelecimentos consumidores recebida com sucesso.
        /// </summary>
        public static string GetCommercesSuccess {
            get {
                return ResourceManager.GetString("GetCommercesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de consumidores.
        /// </summary>
        public static string GetConsumersError {
            get {
                return ResourceManager.GetString("GetConsumersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de consumidores recebida com sucesso.
        /// </summary>
        public static string GetConsumersSuccess {
            get {
                return ResourceManager.GetString("GetConsumersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao gerar token.
        /// </summary>
        public static string GetGeneratedTokenError {
            get {
                return ResourceManager.GetString("GetGeneratedTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token gerado com sucesso.
        /// </summary>
        public static string GetGeneratedTokenSuccess {
            get {
                return ResourceManager.GetString("GetGeneratedTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de mercados.
        /// </summary>
        public static string GetMarketsError {
            get {
                return ResourceManager.GetString("GetMarketsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de mercados recebida com sucesso.
        /// </summary>
        public static string GetMarketsSuccess {
            get {
                return ResourceManager.GetString("GetMarketsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de estados.
        /// </summary>
        public static string GetStatesError {
            get {
                return ResourceManager.GetString("GetStatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de estados recebidas com sucesso.
        /// </summary>
        public static string GetStatesSuccess {
            get {
                return ResourceManager.GetString("GetStatesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao receber lista de usúarios.
        /// </summary>
        public static string GetUsersError {
            get {
                return ResourceManager.GetString("GetUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de usúarios recebida com sucesso.
        /// </summary>
        public static string GetUsersSuccess {
            get {
                return ResourceManager.GetString("GetUsersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar estabelecimento consumidor.
        /// </summary>
        public static string SaveCommerceError {
            get {
                return ResourceManager.GetString("SaveCommerceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estabelecimento consumidor salvo com sucesso.
        /// </summary>
        public static string SaveCommerceSuccess {
            get {
                return ResourceManager.GetString("SaveCommerceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar consumidor.
        /// </summary>
        public static string SaveConsumerError {
            get {
                return ResourceManager.GetString("SaveConsumerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consumidor salvo com sucesso.
        /// </summary>
        public static string SaveConsumerSuccess {
            get {
                return ResourceManager.GetString("SaveConsumerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar mercado.
        /// </summary>
        public static string SaveMarketError {
            get {
                return ResourceManager.GetString("SaveMarketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mercado salvo com sucesso.
        /// </summary>
        public static string SaveMarketSuccess {
            get {
                return ResourceManager.GetString("SaveMarketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar telefone.
        /// </summary>
        public static string SavePhoneError {
            get {
                return ResourceManager.GetString("SavePhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone salvo com sucesso.
        /// </summary>
        public static string SavePhoneSuccess {
            get {
                return ResourceManager.GetString("SavePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro, usúario já existe na base.
        /// </summary>
        public static string SaveUserAlreadyExists {
            get {
                return ResourceManager.GetString("SaveUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar usúario.
        /// </summary>
        public static string SaveUserError {
            get {
                return ResourceManager.GetString("SaveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usúario salvo com sucesso.
        /// </summary>
        public static string SaveUserSuccess {
            get {
                return ResourceManager.GetString("SaveUserSuccess", resourceCulture);
            }
        }
    }
}
